# Site settings
title: danicodes
description: 'moving from confusion to understanding with data'
url: 'http://danicodes.github.io'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'

author:
  name: 'Danielle Williams'
  email: danicodes94@gmail.com
  twitter_username: dannicodes
  github_username:  danicodes
  linkedin_username:  danicodes

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
