# Site settings
title: everydata
description: 'data is cool'
url: 'http://danicodes.github.io' 
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'

author:
  name: 'Daniell Williams'
  email: d.liza.williams11@gmail.com
  twitter_username: dannicodes
  github_username:  danicodes
  linkedin_username:  danicodes


# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: pygments

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
